Front invite page
jurciusmantas/PSK pull request #27
Opened 2020-03-18 09:04 UTC by tomaBurn

Langas registracijos pakvietimui išsiųsti. Įvestam el. pašto adresui yra išsiunčiamas sugeneruotas randon token'as, kuris vėliau prisidės prie link'o į registracijos langą.

2020-03-18 14:58 UTC, jurciusmantas requested changes

2020-03-18 14:58 UTC, jurciusmantas commented on PSK.UII/ClientApp/src/routes/Routes.js
> +                        <Route path='/invite' exact component={InvitePage} />
Čia nereikia exact. Exact nurodo default'inį.

2020-03-18 14:58 UTC, jurciusmantas commented on PSK.Model/Services/InviteService.cs
> +        MockDBConnection db = new MockDBConnection();
Šitą reikia įsi'injectint per serviso konstruktorių (kaip ir į controlerį įsi'injectinai patį InviteService).

2020-03-18 14:58 UTC, jurciusmantas commented on PSK.Model/Services/InviteService.cs
> +            SmtpServer.Credentials = new System.Net.NetworkCredential("noreply.megstamkumpi@gmail.com", "labai5l4pt45");
Nebaisu į public repositoriją dėt credentialus? :D

2020-03-18 14:58 UTC, jurciusmantas commented on PSK.UII/Controllers/InviteController.cs
> +        }
?
Jeigu palikta ateičiai, tai gal ateičiai ir pasidarysim

2020-03-22 17:31 UTC, jurciusmantas commented
isimergink naujausia masteri ir we are ready to go

2020-03-23 12:56 UTC, merged

2020-03-24 09:21 UTC, mr-frying-pan commented on PSK.Model/Services/InviteService.cs
> +            SmtpServer.Credentials = new System.Net.NetworkCredential("noreply.megstamkumpi@gmail.com", "labai5l4pt45");
Jau per vėlu :D