Logging
jurciusmantas/PSK pull request #29
Opened 2020-03-24 08:58 UTC by mr-frying-pan

2020-03-24 21:28 UTC, jurciusmantas requested changes
Bendras vaizdas: nemanau, kad pasirinktas yra geras approach'as. Dabar įsivaizduok, jeigu turėtum 100 servisų - tai reikėtų papildomų dar 100 klasių kaip jų dekoratorių vien log'inimui?

Manau galima būtų padaryti žymiai papraščiau. Tiesiog vienas log'inimo servisas, ir visi kiti servisai jį įsi'injectina ir naudojasi to serviso metodais log'inimui.

2020-03-24 21:28 UTC, jurciusmantas commented on PSK.Model/Logging/LoginLoggingDecorator.cs
> +                _logger.Information("{Timestamp} {Login}: {DecorateeClassName}.Login success", result.Data.Login, _decorateeClassName);
Jeigu lūš eilutėje viršiau (pagrindiniame login'o serviso metod'e), tada įlogins info tik tuo atveju, jeigu žemiau irvėl bus try-catch blokas. info log'as išvis turėtų būti pačioj pradžioj metodo, pati pirma metodo eilutė, dar net prieš try-catch bloką

2020-03-24 21:28 UTC, jurciusmantas commented on PSK.Model/Logging/LoginLoggingDecorator.cs
> +                _logger.Information(e, "{Timestamp} {Login}: {DecorateeClassName}.Login failed {Newline} {Exception}", args.Login, _decorateeClassName);
čia jau nebe info levelio log'as, o error

2020-03-24 21:28 UTC, jurciusmantas commented on PSK.Model/Logging/LoginLoggingDecorator.cs
> +                throw; // perhaps we'd like to hide original exception from the database and 'throw e;' would be more suitable
Pastabos tos pačios iš viršutinio metodo

2020-03-24 21:28 UTC, jurciusmantas commented on PSK.UII/ClientApp/src/components/Login/LoginPage.js
> +    //}
Jeigu nusprendžiam, kad kodo nebereikia - tai ir trinam jį

2020-03-25 18:52 UTC, mr-frying-pan reviewed
Dėl bendro vaizdo:
Visų pirma tai techniniuose reikalavimuose yra toks dalykas, kad reikia interceptoriaus arba dekoratoriaus.
Kitas dalykas yra kad jei mes dedam į Service'us tai prie business logika apauga ne business dalykais, ko turbūt reikėtų vengti.
Sutinku dėl tų 100 interface'ų. Dėl to pradžioj bandžiau padaryt su interceptorium, bet SimpleInjectorius nelabai palaiko interceptoriaus injectinimo. Teoriškai galima, bet ten reikalinga System.Runtime.Remoting, kurios ant .NET Core nėra.

2020-03-25 18:52 UTC, mr-frying-pan commented on PSK.Model/Logging/LoginLoggingDecorator.cs
> +                _logger.Information("{Timestamp} {Login}: {DecorateeClassName}.Login success", result.Data.Login, _decorateeClassName);
Man atrodo, kad taip ir turi būti. Šitas log'as loggina, kad user'is įsiloginino sėkmingai. Tai to negalima žinoti pačioj pradžioj.
Jei lūžta Login'as tai tam yra catch apačioj

2020-03-25 18:52 UTC, mr-frying-pan commented on PSK.Model/Logging/LoginLoggingDecorator.cs
> +                _logger.Information(e, "{Timestamp} {Login}: {DecorateeClassName}.Login failed {Newline} {Exception}", args.Login, _decorateeClassName);
Kol kas tas service'as throwina ArgumentNullException tuo atveju kai loginas arba passwordas yra null arba tušti. Tai čia gal nevisiškai erroras. Bet iš principo sutinku, gali kažkas kitas tą patį exceptioną throwint.

Pradžiai tikrai pridėsiu Exception catchą apačioj, kuris logintų errorą. To tikrai reikia

2020-03-25 20:50 UTC, jurciusmantas commented
Nu gerai, galima sukurti atskira projektą "PSK.Helpers", kur būtų logginimas, visokios hash'ų operacijos ir panašiai, jeigu jau taip nenorim, kad modelyje būtų loginimo logika. Nors realiai loginimą tenaudos modelis, tai irgi nematau čia bėdos.
Kad interceptoriaus arba dekoratoriaus reikia, tai nemanau, kad su juo reikėtų implementuoti betką. Tikrai nuoširdžiai manai, kad gera idėja kiekvienam servisui atskirai kurti po naują dekoratoriaus klasę vien loginimui?

2020-03-26 08:39 UTC, mr-frying-pan commented
![image](https://user-images.githubusercontent.com/31473299/77625268-f4e37880-6f4b-11ea-8932-40c4d263e27b.png)
Čia yra iš techninių reikalavimų.
Taip, galima prikabint dar vieną papildomą injectinimo frameworką vien tik tam, kad injectint interceptorius, bet tada mes turim 2 dependency injection frameworkus. Dekoratorių pasirinkau, nes tą siūlo SimpleInjectoriaus doc'sai.

Taip, aš sutinku, kad 100 servisų (ko mes neturėsim) turėt 100 dekoratorių nėra labai nuostabu, ir tą reikės refactorint šiek tiek, nes kol kas bus kodo pasikartojimų, bet tą galima padaryt. Ir supaprastina metodus, kas yra labiau SOLID

2020-04-08 15:05 UTC, jurciusmantas approved these changes

2020-04-21 17:57 UTC, merged