Front registration
jurciusmantas/PSK pull request #31
Opened 2020-03-25 14:11 UTC by tomaBurn

Registracijos langas, gaunamas atidarius link'a su token'u. Vartotojui užsiregistravus, atnaujinami jo duomenys duomenų bazėj, token'as pašalinamas. Bandant atidaryt registracijos langą su neegzistuojančiu token'u rodo pranešimą vietoj registracijos formos.

2020-03-25 19:26 UTC, mr-frying-pan approved these changes
Netikrinau ar veikia, bet rodos normaliai viskas

2020-03-25 19:26 UTC, mr-frying-pan commented on PSK.Model/Services/InviteService.cs
> +            mail.Body = "https://localhost:44395/registration/" + token;
Šitą reikės pakeist į dalyką imamą iš config'o

2020-03-25 19:26 UTC, mr-frying-pan commented on PSK.Model/Services/RegistrationService.cs
> +                emp.Name = string.Concat(args.FirstName, " ", args.LastName);
O gal geriau, jei jau taip darom, tiesiog padaryt FullName RegistrationArgs'uose?

2020-03-27 07:14 UTC, jurciusmantas requested changes

2020-03-27 07:14 UTC, jurciusmantas commented on PSK.UII/ClientApp/src/components/Registration/RegistrationPage.js
> +    componentWillMount = () => {
![image](https://user-images.githubusercontent.com/37446816/77731077-e314da80-700a-11ea-8456-9730d70e1017.png)
(source: https://reactjs.org/docs/react-component.html )
Geriau pakeisit į componentDidMount, o kadangi po request'o vistiek yra setState({..}), tai komponentas vistiek persipieš

2020-03-27 08:18 UTC, jurciusmantas commented
Tuo pačiu šitame branche siųlyčiau sutvarkyti navigaciją:
![image](https://user-images.githubusercontent.com/37446816/77735846-eeb8cf00-7013-11ea-8c85-b09d0a9874f8.png)

Šitas išėjo su praeitu branch'u (FRONT_InvitePage), todėl yra tiek dev'e, tiek masteryje. Ten tiesiog NavMenu.js kiekvieną NavLink reikia įwrapp'int į NavItem atskirai

2020-04-06 07:15 UTC, mr-frying-pan commented on PSK.UII/ClientApp/src/components/Registration/RegistrationPage.js
>              repeatedPassword: repeatedPassword,
Kam šitas reikalingas? Paprastai slaptažodžio pakartojimas yra skirtas tam, kad žmogus žinotų, kad įrašė tą ką mano, kad įrašė. Mes tą galim patikrint front'e, nereikia to siųst į back'ą

2020-04-23 15:09 UTC, merged