Front logout
jurciusmantas/PSK pull request #68
Opened 2020-05-03 11:25 UTC by jurciusmantas

2020-05-04 19:24 UTC, mr-frying-pan requested changes
Nemažai minor dalykų, bet Get'ą reikia pakeist į Post'ą

2020-05-04 19:24 UTC, mr-frying-pan commented on PSK.Model/Logging/LoginLoggingDecorator.cs
> +                _logger.Information("{Timestamp} {Login}: {DecorateeClassName}.LoginToken success", null, _decorateeClassName);
Minor, bet:
1. Nereikia {Timestamp}. Žinau, kad pas mane buvo, bet ten negerai, naujausiame turėtų būt tvarkoj
2. Vietoj `null` reiktų įdėti išsilogoutinusio userio loginą
3. Vietoj `LoginToken` turėtų būti `Logout`

2020-05-04 19:24 UTC, mr-frying-pan commented on PSK.Model/Services/ILoginService.cs
> +        void Logout();
Geriau būtų jei returnintų `ServerResult`. Vienodžiau visur

2020-05-04 19:24 UTC, mr-frying-pan commented on PSK.UII/ClientApp/src/components/Layout/NavMenu.js
> +    get("login/logout");
Logoutas turėtų būti su post'u. Get'us browseriai cacheina ir dėl to galim turėt problemų

Susijusi info, jei kam įdomu :D
https://twitter.com/rombulow/status/990684453734203392

2020-05-04 19:24 UTC, mr-frying-pan commented on PSK.UII/ClientApp/src/helpers/cookie.js
> +    let expirationDate = moment().add(15, 'minute').toDate();
Kaip jau rašiau prie kito PR, jei jau turim 15 min tai geriau dėt ne `expires`, o `max-age`. Nereikia nieko skaičiuot

2020-05-04 19:24 UTC, mr-frying-pan commented on PSK.UII/Controllers/LoginController.cs
> +        [HttpGet]
Čia turėtų būti Post arba Put

2020-05-05 14:38 UTC, jurciusmantas commented
Pataisiau į post'ą ir ištryniau dabar login'ą išvis logginime, nes reiktų jį siųsti per POST kaip argumentą, kas biški nesąmonė atrodo.
Suprantu, kad dabar tas logg'inimas logout'o atrodo bereikšmis (nes ten neįlogins jokios info kas atlieka veiksmą), tačiau geriau reikėtų pasidaryti kažkokį session scoped servisą SessionDataService, kur galėtumėm iš betkurios vietos pasiekt prisijungusį employee ir nereiktų siuntinėt visokių login'ų ar employeeId visur.

2020-05-06 07:59 UTC, mr-frying-pan approved these changes

2020-05-09 04:53 UTC, merged